### ISSUE TITLE
gradle setup

### ISSUE THREAD

**Issue by jjhesk** [orhanobut/wasp#76] opened 2015-03-09 07:04 UTC
is this possible to have a gradle setup for us?

**Comment by kardeslik** [comment] 2015-03-09 09:05
Sorry, I did not get what you mean by "gradle setup"? Can you explain in detail?

**Comment by orhanobut** [comment] 2015-03-16 08:56
I think the problem is solved, no reply yet. I close it.

**Closed by orhanobut** 2015-03-16 08:56 UTC

**Comment by jjhesk** [comment] 2015-03-22 14:34
done!
